#!/usr/bin/env python3
"""Panel-20260830 N17: window duration vs within-window squint sweep.

Paper claims (apparent contradiction):
  L685: windows "spanning several minutes"
  ablation L119: within-window squint sweeps ~20--35 deg
Reports actual distributions: window width (s), within-window |psi_sq| sweep,
and |psi_sq| drift over any 30 s sub-interval (dwell time).
"""
import pickle, sys
from pathlib import Path
import numpy as np

_PROJ = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJ.parent.parent / "src"))

from sar_sim.solver.types import build_agile_instance, precompute_geometry

SCEN = _PROJ / "experiments" / "scenarios"
SLEW_RATE, SETTLE_TIME = 0.0524, 5.0
STEP = 10.0

widths, sweeps, drift30 = [], [], []
for g in ["S1", "S2", "S3", "S4"]:
    pkls = sorted((SCEN / g).glob("*.pkl"))[:5]
    g_w, g_s, g_d = [], [], []
    for p in pkls:
        data = pickle.load(open(p, "rb"))
        inst = build_agile_instance(data.get("windows", []), data.get("targets", []),
                                    max_slew_rate=SLEW_RATE, settle_time=SETTLE_TIME)
        precompute_geometry(inst, step_s=STEP)
        # Pickle source: first-party scenario files generated by this repo's
        # generate_all_scenarios.py (same trust basis as r_visible_envelope.py).
        for i, task in enumerate(inst.tasks):
            t = task.t_earliest
            psis = []
            while t <= task.t_latest:
                try:
                    psis.append(abs(inst.geom_cache.lookup(i, t).psi_sq))
                except Exception:
                    pass
                t += STEP
            if len(psis) >= 2:
                psis = np.degrees(psis)
                w = (task.t_latest - task.t_earliest) / 60.0
                g_w.append(w)
                g_s.append(psis.max() - psis.min())
                for i in range(len(psis) - 3):
                    g_d.append(abs(psis[i + 3] - psis[i]))
    print(f"{g}: window width min/med/p95/max = "
          f"{np.min(g_w):.1f}/{np.median(g_w):.1f}/{np.percentile(g_w,95):.1f}/{np.max(g_w):.1f} min | "
          f"psi sweep med = {np.median(g_s):.1f} deg (p95 {np.percentile(g_s,95):.1f}) | "
          f"30s drift med = {np.median(g_d):.1f} deg (p95 {np.percentile(g_d,95):.1f})")
    widths += g_w; sweeps += g_s; drift30 += g_d
print(f"\nPOOLED: width med {np.median(widths):.1f} min | sweep med {np.median(sweeps):.1f} deg | "
      f"30s drift med {np.median(drift30):.1f} deg p95 {np.percentile(drift30,95):.1f}")
